import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, DM_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interVariable = Inter({
  variable: "--font-inter-variable",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interVariable.variable} ${dmMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <main className="flex-1">{children}</main>
          <footer
            className="border-t border-border/50 px-6 py-4 text-[11px] text-muted-foreground tracking-wide"
            style={{ fontFamily: "var(--font-dm-mono)" }}
          >
            By Willie —{" "}
            <a
              href="https://github.com/shrimbly/easy-peasy-ease"
              className="underline hover:text-foreground transition-colors"
              target="_blank"
              rel="noreferrer"
            >
              gh
            </a>{" "}
            —{" "}
            <a
              href="https://x.com/ReflctWillie"
              className="underline hover:text-foreground transition-colors"
              target="_blank"
              rel="noreferrer"
            >
              x
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
